import { Button } from "std-widgets.slint";

export component HotBar inherits Window {
    width: 860px;
    height: 480px;
    background: transparent;

     in-out property <bool> hotbar_enabled: true;

     in-out property <int> event_multiple_download_rogress;


    HotBar := Rectangle {
        width: 380px;
        height: 60px;
        background: #0B0A0A;
        border-radius: 16px;

        y: hotbar_enabled ? 0px : 40px;   //  oдин px
        opacity: hotbar_enabled ? 0.0 : 1.0;

        animate y, opacity {
            duration: 160ms;        //  tолько ms
            easing: ease-out; //плавное появление
        }

        Text {
            x: 70px;
            text: "create-common.toml";
            font-size: 14px;
            color: #989898;

            vertical-alignment: center;
        }

        Text {
            x: 300px;
            text: event_multiple_download_rogress;
            font-size: 14px;
            color: #989898;
            vertical-alignment: center;

        }
    }
}