import {Button} from "std-widgets.slint";

export component Login inherits Window {
    z: 1;
    width: 380px;
    height: 480px;
    background: transparent;

    default-font-family: "Inter";
    default-font-size: 13px;
    default-font-weight: FontWeight.bold;

    in-out property<bool> is_open_login: false;
    visible: is_open_login;

    in-out property <string> error_input;
    in-out property <string> username;
    in-out property <string> passwords;

    Rectangle {
        width: 100%;
        height: 100%;
        background: #0B0A0A;
        opacity: 1;
    }
//----------------------------------------------------------------------------------------------------
    Rectangle {
        Text {
                x: 30px;
                y: 75px;
                text: "Никнейм";
                color: #969696;
            }
        Rectangle {
            x: 20px;
            y: 100px;
            width: 340px;
            height: 60px;
            clip: true;
            background: #212121;
            border-radius: 12px;


            TextInput {
                   x: 10px;
                   font-size: 14px;
                   text: "username";
                   width: max(parent.width, self.preferred-width);
                   vertical-alignment: center;
            }
        }
    }
//-----------------------------------------------------------------------------------------------------
    Rectangle {
        Text {
            x: 30px;
            y: 190px;
            text: "Пароль";
            color: #969696;
        }
        Rectangle {
            x: 20px;
            y: 215px;
            width: 340px;
            height: 60px;
            clip: true;
            background: #212121;
            border-radius: 12px;


            TextInput {
                x: 10px;

                font-size: 14px;
                input-type: password;  //некоректно роботает выделение текста в поле пароль
                text: "password";
                width: max(parent.width, self.preferred-width);
                vertical-alignment: center;

            }
        }
    }
//-----------------------------------------------------------------------------------------------
    Rectangle {
         x: 5px;
         y: 320px;
         width: 260px;
         height: 25px;

        Text{
            text: "никнейм не должен содержать"; //error_input
            color: #E03A3A;
            horizontal-alignment: left;
        }
    }
//--------------------------------------------------------------------------------------------------
    Rectangle {
          x: parent.width - 180px;
          y: 400px;
          width: 160px;
          height: 45px;
          border-radius: 100px;
          clip: true;
          background:#238636;

          Text {
            text: "Авторизоваться";

          }


          Button {
            width: 100%;
            height: 100%;

          }

    }

//--------------------------------------------------------------------------------------------------
    Rectangle {
          x: 20px;
          y: 400px;
          width: 160px;
          height: 45px;
          border-radius: 100px;
          clip: true;
          background:#E03A3A;

          Text {
            text: "Зарегистрироваться";

          }

          Button {
            width: 100%;
            height: 100%;

          }

    }

//--------------------------------------------------------------------------------------------------



    Rectangle {
         x: parent.width - 85px;
         y: 30px;
         width: 50px;
         height: 50px;
         border-radius: 16px;
         clip: true;
         
         Button {
             width: 100%;
             height: 100%;
             icon: @image-url("image/exit.png");
             icon-size: 16px;

             clicked => {
                is_open_login = false;

             }
         }
    }
}