import {Button} from "std-widgets.slint";

export component Login inherits Window {
    z: 1;
    width: 380px;
    height: 480px;
    //width: 100%;
    //height:100%;
    background: transparent;


    in-out property<bool> is_open_login: false;
    visible: is_open_login;


    Rectangle {
        width: 100%;
        height: 100%;
        background: #0B0A0A;
        opacity: 0.85;

        Text {
            x: (parent.width - self.width) / 2;
            y: 30px;
            text: "Логин";
            color: #ffffff;
            font-size: 28pt;
            font-family: "Inter";
            font-weight: FontWeight.extra-bold;
        }
    }

    Rectangle {
         x: parent.width - 85px;
         y: 30px;
         width: 50px;
         height: 50px;
         border-radius: 16px;
         clip: true;
         Button {
             width: 100%;
             height: 100%;
             icon: @image-url("image/exit.png");
             icon-size: 16px;

             clicked => {
                is_open_login = false;

             }
         }
    }
}