import { Button } from "std-widgets.slint";
import { Settings } from "./settings.slint";
import { Login } from "login.slint";


export component MainWindow inherits Window {

    z: 0;
    max-width: 860px;
    min-width: 860px;
    max-height: 480px;
    min-height: 480px;
    in-out property<bool> is_settings_open <=> settings_window.is_open_settings;
    in-out property<bool> is_login_open <=> login_window.is_open_login;

//------------------------------------------------------------------------------------
    Image {
        width: 860px;
        height: 480px;
        source: @image-url("image/bg.jpg");
    }
//------------------------------------------------------------------------------------
    Text {
        x: 100px; y: 225px;
        text: "OLIVIA CREATE";
        color: #ffffff;
        font-size: 28pt;
        font-family: "Inter";
        font-weight: FontWeight.extra-bold;
    }
//------------------------------------------------------------------------------------
    Rectangle {
        x: parent.width - 100px; y:40px;
        width: 60px;
        height: 60px;
        background: #006D35;
        border-radius: 20px;
        border-width: 8px;
        border-color: #0B0A0A;

        clip: true;

        Button {
            width: 100%;
            height: 100%;
            icon: @image-url("image/user.png");
            icon-size: 26px;
            enabled: !is_settings_open && !is_login_open;

            clicked => {
                login_window.is_open_login = true;
                debug("user");
            }
        }
    }
    login_window := Login {
        x:(parent.width - self.width) / 2;
        y:(parent.height - self.height) / 2;
        is_open_login: false;
    }
//------------------------------------------------------------------------------------
    in-out property <string> play_button_status;
    in-out property <color> play_button_status_color: #006D35;
    in-out property <bool> play_button_look: false;
    
    callback button_play_run;
    Rectangle {
        x:100px;  y:300px;
        width: 160px;
        height: 60px;
        background: play_button_status_color;
        border-radius: 16px;
        clip: true;

        Text {
            text: play_button_status;
            color: #ffffff;
            font-size: 12pt;
            font-family: "Inter";
            font-weight: FontWeight.bold;
        }

        Button {
            width: 100%;
            height: 100%;
            primary: false;
            text: "                             ";
            icon: @image-url("image/play.png");
            icon-size: 26px;
            enabled: !is_settings_open && !is_login_open && !play_button_look;  // замораживание нажатие если открыты насройки

            clicked => {
                debug("Иди нах");
                button_play_run();

            }
        }
    }
//------------------------------------------------------------------------------------
    Rectangle {
        x: 280px; y:300px;
        width: 60px;
        height: 60px;
        background: #0B0A0A;
        border-radius: 16px;
        clip: true;

        Button {
            width: 100%;
            height: 100%;
            icon: @image-url("image/settings.png");
            icon-size: 26px;
            enabled: !is_settings_open && !is_login_open;
            clicked => {
                settings_window.is_open_settings = true;
            }
        }
    }

    settings_window := Settings {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        is_open_settings: false;  //по умолчанию
    }
//------------------------------------------------------------------------------------
    in-out property <bool> hotbar_enabled: true;
    in-out property <string> event_multiple_download_rogress;
    in-out property <string> event_multiple_download_text;


        HotBar := Rectangle {
            width: 380px;
            height: 60px;
            background: #0B0A0A;
            border-radius: 16px;

            y: hotbar_enabled ? 0px : 40px;   //  oдин px
            opacity: hotbar_enabled ? 0.0 : 1.0;

            animate y, opacity {
                duration: 160ms;        //  tолько ms
                easing: ease-out; //плавное появление
            }

            Text {
                x: 70px;
                text: event_multiple_download_text;
                font-size: 14px;
                color: #989898;

                vertical-alignment: center;
            }

            Text {
                x: 300px;
                text: event_multiple_download_rogress;
                font-size: 14px;
                color: #989898;
                vertical-alignment: center;

            }
        }

}
//------------------------------------------------------------------------------------
